Repository Standard-Structure/struct, pull requests merged in 2020-05, with the labels that each got.

#4 Jest CI
  .github/workflows/jest.yml
  README.md
Labels: ci/cd

#8 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#10 Format CI
  .github/workflows/format.yml
  README.md
  src/commands/cli.ts
  src/commands/generate.ts
  src/extensions/cli-extension.ts
Labels: ci/cd

#11 Correct network-check unit testing to proper directory
  __tests__/network-check.test.ts
  package-lock.json
  package.json
Labels: bug
